# Случайная выборка

## Задание 1. Объяснить различие между кодом

In [1]:
import numpy as np
a = np.array([6, 6, 6, 7, 7, 7, 7, 7, 7])

In [2]:
a[np.random.randint(len(a), size=5)]

array([6, 7, 7, 7, 7])

## и кодом

In [3]:
np.random.randint(6, 8, 5)

array([6, 7, 6, 6, 7])

### Ответ: В первом массиве значения определены заранее, после чего выбраны случайным образом. Во втором коде генерируется массив из 5 случайных чисел в диапазоне от 6 до 8.

## Задание 2. В примере 2 использовался метод np.random.random_integers для выборки из равномерного распределения по числам с плавающей точкой [1/2, 3/2, 5/2, 7/2]. Как можно сделать то же самое, воспользовавшись методом np.random.randint?

In [4]:
a = [1/2, 3/2, 5/2, 7/2]

a = np.array(a)
a[np.random.randint(len(a), size=5)]

array([0.5, 1.5, 1.5, 2.5, 1.5])

## Задание 3. Американская лотерея Mega Millions во время написания этой книги использовала выбор 5 чисел из 70 и одного из 25. Джекпот распределяется между игроками, выбравшими номера, совпадающие со случайно выбранными. Какова вероятность выиграть джекпот? Написать однострочный код Python, используя библиотеку NumPy, для выбора набора случайных чисел для игрока.

In [5]:
main_numbers = np.random.choice(range(1, 72), size=5, replace=False)

mega_ball = np.random.choice(range(1, 26), size=1)

print("Main numbers: ", main_numbers)
print("Mega Ball: ", mega_ball)

Main numbers:  [44 38 14 30 26]
Mega Ball:  [4]
